import React from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Privacy Policy | Vaulty',
  description: 'Learn how Vaulty handles your data, media, and privacy.',
};

export default function PrivacyPolicy() {
  const lastUpdated = 'August 24, 2026';

  return (
    <>
      <Navbar />
      <main className="wrap section" style={{ maxWidth: '800px', margin: '0 auto', padding: '64px 24px', lineHeight: '1.6' }}>
        <div style={{ marginBottom: '48px' }}>
          <h1 style={{ fontSize: '36px', letterSpacing: '-0.02em', marginBottom: '8px' }}>Privacy Policy</h1>
          <p style={{ color: 'var(--text-dim)', margin: 0 }}>Last Updated: {lastUpdated}</p>
        </div>

        <section style={{ display: 'flex', flexDirection: 'column', gap: '32px' }}>
          <div>
            <h2>1. Introduction</h2>
            <p>
              Welcome to Vaulty. We build tools that make it easy to collect and share photos from your events. 
              This Privacy Policy explains how we collect, use, and protect your information when you use our website and services. 
              By using Vaulty, you agree to the practices described in this policy.
            </p>
          </div>

          <div>
            <h2>2. Information We Collect</h2>
            <p>We collect information you provide to us directly and information generated automatically by your use of our service.</p>
            
            <h3 style={{ marginTop: '16px', fontSize: '18px' }}>Information You Provide</h3>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Host Accounts:</strong> If you create a host account to manage events, we collect your email address, name, and a securely hashed version of your password. We do not store plaintext passwords.</li>
              <li><strong>Guest Information:</strong> If you join an event as a guest, you are not required to create an account. You may optionally provide a display name so the host and other guests can identify your uploads.</li>
              <li><strong>Media:</strong> We collect the photos and videos you upload to an event.</li>
            </ul>

            <h3 style={{ marginTop: '16px', fontSize: '18px' }}>Information Collected Automatically</h3>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>IP Addresses & Security Logs:</strong> We temporarily log IP addresses for security purposes, such as rate-limiting event joins to prevent brute-force guessing of event codes.</li>
              <li><strong>Device Identifiers:</strong> We may collect device tokens generated by our mobile companion app (if used) to associate uploads with your specific device and allow you to manage them.</li>
              <li><strong>Usage Analytics:</strong> We use Vercel Analytics to collect aggregate, anonymized usage data (such as page views and general interaction metrics) to help us improve the service.</li>
            </ul>
          </div>

          <div>
            <h2>3. Google APIs and Google Drive Data</h2>
            <p>
              Vaulty uses the Google Drive API to reliably store the photos and videos uploaded to events. <strong>End users do not connect their personal Google accounts or personal Google Drives to Vaulty.</strong>
            </p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Vaulty&apos;s Infrastructure:</strong> The Google Drive account used to store media is controlled and managed entirely by Vaulty. It acts as our backend storage infrastructure.</li>
              <li><strong>Limited Use:</strong> Our use of the Google Drive API is strictly limited to uploading, organizing, and serving the media you share to Vaulty events.</li>
              <li><strong>No Data Sale or AI Training:</strong> Data processed through our Google API integration is never sold to third parties, used for advertising, or used to train generalized AI/ML models.</li>
              <li><strong>Compliance:</strong> Our use of data obtained from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements.</li>
            </ul>
          </div>

          <div>
            <h2>4. Public Events and Shared Media</h2>
            <p>
              Vaulty is designed for sharing photos with event attendees. You should not upload highly sensitive or private material to an event.
            </p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Event Access:</strong> Anyone who has the correct event link, QR code, or PIN can access the event gallery and view the media uploaded to it.</li>
              <li><strong>File URLs:</strong> To serve images quickly, files stored in our Google Drive infrastructure are configured as &quot;anyone with the link can view.&quot; While the Vaulty interface restricts gallery access to authenticated event guests, the underlying direct file URL could be accessed by anyone who obtains it.</li>
            </ul>
          </div>

          <div>
            <h2>5. Third-Party Services</h2>
            <p>We use trusted third-party service providers to operate Vaulty. These include:</p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Google:</strong> For Google Drive API storage infrastructure.</li>
              <li><strong>Vercel:</strong> For application hosting, Vercel Blob (temporary, transient upload staging), and Vercel Analytics.</li>
              <li><strong>Firebase (Google):</strong> For our database (Firestore) to store event metadata and host account records.</li>
            </ul>
            <p style={{ marginTop: '8px' }}>
              These providers may process or store information in countries other than your own. This includes regions where their infrastructure operates.
            </p>
          </div>

          <div>
            <h2>6. Data Deletion and Retention</h2>
            <p>We provide mechanisms to delete your data:</p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Guest Uploads:</strong> Guests receive a temporary deletion token when they upload media, allowing them to delete their own uploads for up to 24 hours. Guests cannot delete media uploaded by others.</li>
              <li><strong>Event Deletion:</strong> Hosts can delete their events at any time. When an event is deleted, Vaulty automatically deletes the associated Google Drive folder containing all media and purges the media records from our database.</li>
              <li><strong>Host Account Deletion:</strong> Currently, host account deletion is not available as a self-service button in the dashboard. To request permanent deletion of your host account and all associated data, please contact us at the email below.</li>
            </ul>
          </div>

          <div>
            <h2>7. Cookies and Local Storage</h2>
            <p>Vaulty uses functional cookies and browser storage to make the service work. We do not use third-party advertising or tracking cookies.</p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li><strong>Functional Cookies:</strong> We use strictly necessary cookies (e.g., <code>vaulty_host_session</code> and <code>vaulty_guest_...</code>) to maintain your login session and event access authorization.</li>
              <li><strong>Local Storage:</strong> We use browser local storage to remember your UI preferences, such as your light/dark mode selection (<code>vaulty-theme</code>).</li>
            </ul>
          </div>

          <div>
            <h2>8. Security</h2>
            <p>
              We implement reasonable security measures to protect your data, including HTTPS for encrypted transport, secure one-time passwords (OTP) for applicable authentication flows, and bcrypt password hashing. However, no system is perfectly secure, and we cannot guarantee absolute security.
            </p>
          </div>

          <div>
            <h2>9. Children&apos;s Privacy</h2>
            <p>
              Vaulty is not intentionally directed toward children under the age of 13 (or the applicable age of consent in your jurisdiction). We do not knowingly collect personal information from children. If we learn we have collected such information, we will delete it.
            </p>
          </div>

          <div>
            <h2>10. Your Privacy Rights</h2>
            <p>
              Depending on where you live and the laws that apply to you (such as the GDPR, CCPA, or the Kenya Data Protection Act, 2019), you may have certain rights regarding your personal information. These may include the right to:
            </p>
            <ul style={{ paddingLeft: '24px', marginTop: '8px', display: 'flex', flexDirection: 'column', gap: '8px' }}>
              <li>Access the personal data we hold about you.</li>
              <li>Request correction of inaccurate data.</li>
              <li>Request deletion of your data.</li>
              <li>Object to or restrict the processing of your data.</li>
              <li>Withdraw consent, where processing is based on consent.</li>
            </ul>
            <p style={{ marginTop: '8px' }}>To exercise these rights, please contact us using the information below.</p>
          </div>

          <div>
            <h2>11. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy or wish to request account deletion, please contact us at:</p>
            <p style={{ marginTop: '8px', fontWeight: '600' }}><a href="mailto:support@vaulty.studio" style={{ color: 'inherit', textDecoration: 'underline' }}>support@vaulty.studio</a></p>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
